# Generated by Django 5.0 on 2023-12-07 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='content',
        ),
    ]
